# Generated by Django 4.2 on 2025-06-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_branch_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Appointments'},
        ),
    ]
