# Generated by Django 4.2 on 2025-06-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, help_text='City/Town', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP Code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented'), ('under_offer', 'Under Offer')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, help_text='State/County/Region', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street number and name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='epc_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/epc/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/floor_plans/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Asking price if for sale, monthly rent if for rent', max_digits=12),
        ),
    ]
