# Generated by Django 4.2 on 2025-06-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_address_remove_property_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='epc_image',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='floor_plan_image',
        ),
        migrations.AddField(
            model_name='property',
            name='epc_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/epc/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/floor_plans/%Y/%m/%d/'),
        ),
    ]
