# Generated by Django 4.2 on 2025-06-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_propertyimage_epc_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='branch',
        ),
    ]
